export default {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
    PHRASES_LOADED: 'PHRASES_LOADED',
    FETCH_PHRASES_FAILURE: 'FETCH_PHRASES_FAILURE',
    REMOVE_PHRASE: 'REMOVE_PHRASE',
};